name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Docker Login
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}

    # Set up variables for tags (latest and commit SHA)
    - name: Set up Docker image tags
      id: vars
      run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    # Build Docker image with both 'latest' and commit SHA as tags
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile \
          --tag "${{ vars.DOCKER_USER }}/${{ vars.DOCKER_REPO_NAME }}:latest" \
          --tag "${{ vars.DOCKER_USER }}/${{ vars.DOCKER_REPO_NAME }}:${{ env.COMMIT_SHA }}"

    # Push both tags to the Docker registry
    - name: Push Docker image
      run: |
        docker push "${{ vars.DOCKER_USER }}/${{ vars.DOCKER_REPO_NAME }}:latest"
        docker push "${{ vars.DOCKER_USER }}/${{ vars.DOCKER_REPO_NAME }}:${{ env.COMMIT_SHA }}"
